package com.healthcare.interop.common.enums;

public enum EhrOperationType {
    GET_PATIENT,
    SAVE_PATIENT,
    UPDATE_PATIENT,
    DELETE_PATIENT,
    GET_ENCOUNTER,
    SAVE_ENCOUNTER,
    UPDATE_ENCOUNTER,
    GET_OBSERVATION,
    SAVE_OBSERVATION,
    GET_CONDITION,
    SAVE_CONDITION,
    GET_MEDICATION_REQUEST,
    SAVE_MEDICATION_REQUEST,
    GET_ALLERGY,
    SAVE_ALLERGY,
    GET_ORGANIZATION,
    GET_PRACTITIONER,
    SEARCH_PATIENTS
}
